AllCops:
  Exclude:
    - 'db/schema.rb'
    - 'config/development-local.rb'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'
Metrics/LineLength:
  Max: 120
Style/Documentation:
  Enabled: false
Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'config/**/*'
Style/FrozenStringLiteralComment:
  Enabled: false
Style/SymbolArray:
  Enabled: false
Style/EmptyMethod:
  Exclude:
    - 'app/controllers/**/*'
Style/LambdaCall:
  Exclude:
    - 'app/views/api/v1/**/*'
Metrics/MethodLength:
    Exclude:
      - db/**/*
      - spec/**/*
Metrics/AbcSize:
    Exclude:
      - db/**/*
      - spec/**/*
Metrics/BlockLength:
  Enabled: false
Layout/EmptyLineAfterGuardClause:
  Enabled: false
