const constants = {
  LOAD_PRODUCTS: 'LOAD_PRODUCTS',
  LOAD_PRODUCT: 'LOAD_PRODUCT',
  DISPLAY_FLASH_MESSAGE: 'DISPLAY_FLASH_MESSAGE',
  CLEAR_FLASH_MESSAGE: 'CLEAR_FLASH_MESSAGE',
  LOAD_CART: 'LOAD_CART',
  LOAD_ORDERS: 'LOAD_ORDERS',
  LOAD_ORDER: 'LOAD_ORDER',
}

export { constants };
export default constants;